version: '3.5'

services:

  # Disocrd bot service
  discord-bot:
 
    # Building the image
    build:
      context: .
      dockerfile: ./Dockerfile
    # IMPORTANT: If you want to redeploy you will need to change the version number
    image: frontlive-discord-bot:v.0.1.0

    # Standard settings
    container_name: frontlive-discord-bot
    stdin_open: true
    tty: true
    restart: unless-stopped

    # Enviroment
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OWNERS=${OWNERS}
      - THANKS_MESSAGE_CHANNEL_TARGET_ID=${THANKS_MESSAGE_CHANNEL_TARGET_ID}
      - DATABASE_URL=${DATABASE_URL}

